name: Test Next Server

on:
  pull_request:
    paths:
      - "www/**"
  push:
    branches:
      - main
    paths:
      - "www/**"

jobs:
  test-next-server:
    runs-on: ubuntu-latest
    concurrency:
      group: test-next-server-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        working-directory: ./www

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: './www/package.json'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: './www/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test
